# Generated by Django 3.0.8 on 2020-10-12 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200922_1830'),
        ('ratings', '0004_auto_20200928_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='posts.Post', verbose_name='Rating Post'),
        ),
    ]
