# Generated by Django 3.0.8 on 2020-09-21 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Post Title')),
                ('series_title', models.CharField(blank=True, max_length=100, verbose_name='Series Title')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Post Text')),
                ('personal_rating', models.IntegerField(blank=True, verbose_name='Personal Rating')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post Author')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='tags.Tag', verbose_name='Post Tags')),
            ],
        ),
    ]
