# Generated by Django 3.0.8 on 2020-09-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_post'),
        ('posts', '0003_auto_20200902_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='Post Tag'),
        ),
    ]
