# Generated by Django 3.0.8 on 2020-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200902_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_rating',
            field=models.IntegerField(blank=True, verbose_name='User Rating'),
        ),
    ]
