# Generated by Django 3.0.8 on 2020-09-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_post'),
        ('posts', '0006_auto_20200903_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='Post Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_rating',
            field=models.IntegerField(blank=True, verbose_name='User Rating'),
        ),
    ]
