# Generated by Django 3.0.8 on 2020-09-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20200904_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Post Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='personal_rating',
            field=models.IntegerField(blank=True, verbose_name='Personal Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='series_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Series Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.Tag', verbose_name='Post Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Post Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='User Rating'),
        ),
    ]
