# Generated by Django 3.0.8 on 2020-09-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_post'),
        ('posts', '0012_auto_20200917_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag', verbose_name='Post Tags'),
        ),
    ]
