# Generated by Django 3.0.8 on 2020-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200928_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.AddField(
            model_name='tag',
            name='genre',
            field=models.CharField(default='Default', max_length=20, verbose_name='Tag Genre'),
            preserve_default=False,
        ),
    ]
