# Generated by Django 3.0.8 on 2020-09-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_tags'),
        ('tags', '0002_remove_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.Post', verbose_name='Tag Posts'),
        ),
    ]
