# Generated by Django 3.0.8 on 2020-09-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
    ]
